# Generated by Django 5.2.16 on 2026-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작가')),
                ('work', models.CharField(max_length=200, verbose_name='작품')),
                ('source', models.CharField(blank=True, default='고전문학거장50인', max_length=100, verbose_name='출처')),
                ('is_selected', models.BooleanField(default=False, verbose_name='다음 작품으로 선택됨')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='선택 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
            ],
            options={
                'verbose_name': '고전문학 작가·작품 후보 (LiteraryCandidate)',
                'verbose_name_plural': '고전문학 작가·작품 후보 관리 (LiteraryCandidate)',
                'ordering': ['author', 'work'],
            },
        ),
    ]
