# Generated by Django 5.2.16 on 2026-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literary', '0003_add_prolific_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='literarycandidate',
            name='is_produced',
            field=models.BooleanField(default=False, verbose_name='제작완료'),
        ),
    ]
