# Generated by Django 5.2.16 on 2026-07-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='원본 제목')),
                ('original_url', models.URLField(unique=True, verbose_name='원본 기사 링크')),
                ('source_media', models.CharField(max_length=50, verbose_name='언론사')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 일시')),
                ('ai_summary', models.TextField(verbose_name='AI 3줄 요약')),
                ('ai_analysis', models.TextField(verbose_name='AI 투자 관점 분석')),
                ('blog_content', models.TextField(verbose_name='블로그 포스팅용 원고')),
                ('is_premium', models.BooleanField(default=False, verbose_name='유료 구독자 전용 여부')),
                ('is_posted', models.BooleanField(default=False, verbose_name='블로그 자동 발행 완료 여부')),
            ],
        ),
    ]
