# Generated by Django 5.2.16 on 2026-07-08 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(max_length=50, verbose_name='종목명')),
                ('market_type', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장 종류')),
                ('is_active', models.BooleanField(default=True, verbose_name='AI 모니터링 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='analyzedarticle',
            name='applied_template',
            field=models.CharField(choices=[('T1', '템플릿 1 (뉴스 요약형)'), ('T2', '템플릿 2 (종목 분석형)'), ('T3', '템플릿 3 (카드뉴스 대본형)')], default='T1', max_length=5, verbose_name='적용된 템플릿'),
        ),
        migrations.AlterField(
            model_name='analyzedarticle',
            name='blog_content',
            field=models.TextField(verbose_name='블로그/티스토리 포스팅용 원고'),
        ),
        migrations.AlterField(
            model_name='analyzedarticle',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='블로그 자동 발행 완료'),
        ),
        migrations.AlterField(
            model_name='analyzedarticle',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='유료 회원 전용 콘텐츠'),
        ),
        migrations.AddField(
            model_name='analyzedarticle',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='articles.stockitem', verbose_name='관련 종목'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_premium', models.BooleanField(default=False, verbose_name='프리미엄 구독 활성화')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='구독 시작일')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='구독 만료일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='저가')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('trading_amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래금액')),
                ('pred_next_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='AI 내일 예상종가')),
                ('pred_5day_return', models.FloatField(blank=True, null=True, verbose_name='AI 향후 5일 예상수익률')),
                ('up_probability', models.FloatField(blank=True, null=True, verbose_name='상승 확률 (0.0~1.0)')),
                ('down_probability', models.FloatField(blank=True, null=True, verbose_name='하락 확률 (0.0~1.0)')),
                ('trading_signal', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('HOLD', '관망')], default='HOLD', max_length=5, verbose_name='매매 신호')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='articles.stockitem', verbose_name='종목')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
