# Generated by Django 5.2.16 on 2026-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_stockitem_analyzedarticle_applied_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_major_index',
            field=models.BooleanField(default=False, verbose_name='코스피200/코스닥150 편입 여부'),
        ),
    ]
