# Generated by Django 5.2.16 on 2026-07-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_stockitem_is_major_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='상장시가총액'),
        ),
    ]
