# Generated by Django 5.2.16 on 2026-07-09 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_stockitem_market_cap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KAKAO', '카카오톡'), ('GOOGLE', '구글')], max_length=10, verbose_name='가입 경로')),
                ('provider_uid', models.CharField(max_length=191, verbose_name='소셜 서비스 고유 ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='소셜 계정 이메일')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='연동 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='연결된 유저')),
            ],
            options={
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
