# Generated by Django 5.2.16 on 2026-07-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='언론사/매체명')),
                ('rss_url', models.URLField(unique=True, verbose_name='RSS 피드 주소')),
                ('is_active', models.BooleanField(default=True, verbose_name='수집 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True, verbose_name='감지 키워드')),
                ('is_active', models.BooleanField(default=True, verbose_name='수집 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_keywords', to='articles.stockitem', verbose_name='연결된 종목(선택)')),
            ],
        ),
        migrations.AddField(
            model_name='analyzedarticle',
            name='matched_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.newskeyword', verbose_name='매칭된 키워드'),
        ),
    ]
