# Generated by Django 5.2.16 on 2026-07-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_newssource_newskeyword_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['-date', 'stock'], name='stockpred_date_stock_idx'),
        ),
    ]
