# Generated by Django 5.2.16 on 2026-07-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_stockprediction_stockpred_date_stock_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprediction',
            name='stockpred_date_stock_idx',
        ),
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['-date', 'stock', '-id'], name='stockpred_date_stock_idx'),
        ),
    ]
