# Generated by Django 5.2.16 on 2026-07-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_stockprediction_stockpred_date_stock_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장 종류')),
                ('date', models.DateField(verbose_name='날짜')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='지수 종가')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='전일 대비 등락')),
                ('change_pct', models.FloatField(blank=True, null=True, verbose_name='전일 대비 등락률(%)')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('market_type', 'date')},
            },
        ),
    ]
