# Generated by Django 5.2.16 on 2026-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_marketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='지수 고가'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='지수 저가'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='지수 시가'),
        ),
    ]
