# Generated by Django 5.2.16 on 2026-07-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_marketindex_high_price_marketindex_low_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KisAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='접근 토큰')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='발급 시각')),
            ],
        ),
    ]
