# Generated by Django 5.2.16 on 2026-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_kisaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('GAINER', '상승률 상위'), ('LOSER', '하락률 상위')], max_length=10, verbose_name='구분')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='순위')),
                ('ticker', models.CharField(max_length=10, verbose_name='종목코드')),
                ('name', models.CharField(max_length=50, verbose_name='종목명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='현재가')),
                ('change_pct', models.FloatField(verbose_name='전일 대비율(%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
            ],
            options={
                'ordering': ['rank_type', 'rank'],
                'unique_together': {('rank_type', 'rank')},
            },
        ),
    ]
