# Generated by Django 5.2.16 on 2026-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rankedmover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='기준일자')),
                ('is_business_day', models.BooleanField(verbose_name='영업일 여부')),
                ('is_trading_day', models.BooleanField(verbose_name='거래일 여부')),
                ('is_market_open', models.BooleanField(verbose_name='개장일 여부')),
                ('is_settlement_day', models.BooleanField(verbose_name='결제일 여부')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
