# Generated by Django 5.2.16 on 2026-07-10 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_marketholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='세션 키(비로그인 사용자 구분용)')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇')], max_length=10, verbose_name='발화자')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='전송 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='로그인 사용자(비로그인 시 null)')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_key', 'created_at'], name='articles_ch_session_33190f_idx'), models.Index(fields=['user', 'created_at'], name='articles_ch_user_id_664f0a_idx')],
            },
        ),
    ]
