# Generated by Django 5.2.16 on 2026-07-10 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_method', models.CharField(choices=[('GENERAL', '일반 로그인'), ('SIGNUP', '회원가입'), ('KAKAO', '카카오'), ('GOOGLE', '구글')], max_length=10, verbose_name='로그인 방식')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='접속 IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='articles_lo_user_id_e09e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='접속 메뉴(URL name)')),
                ('path', models.CharField(max_length=255, verbose_name='요청 경로')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='접속 IP')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='접속 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', '-accessed_at'], name='articles_me_user_id_03b7ab_idx'), models.Index(fields=['menu_name', '-accessed_at'], name='articles_me_menu_na_bab228_idx')],
            },
        ),
    ]
