# Generated by Django 5.2.16 on 2026-07-10 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_loginlog_menuaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_subscription', models.BooleanField(default=False, verbose_name='뉴스 구독 여부')),
                ('interested_keywords', models.CharField(blank=True, max_length=255, verbose_name='관심 키워드(콤마로 구분)')),
                ('auto_posting_enabled', models.BooleanField(default=False, verbose_name='자동 포스팅 사용 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('WORDPRESS', '워드프레스'), ('TISTORY', '티스토리'), ('NAVER', '네이버 블로그')], max_length=10, verbose_name='포스팅 플랫폼')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='이 플랫폼으로 자동 포스팅 사용')),
                ('account_id', models.CharField(blank=True, max_length=150, verbose_name='계정 ID')),
                ('credential', models.CharField(blank=True, max_length=255, verbose_name='비밀번호 / API Key')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'ordering': ['user', 'platform'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
