# Generated by Django 5.2.16 on 2026-07-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_userpreference_blogpostingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostingaccount',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='사이트 주소(워드프레스만 해당)'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='post_all_articles',
            field=models.BooleanField(default=False, verbose_name='전체 기사 발행(관심 키워드 무시)'),
        ),
        migrations.CreateModel(
            name='PostedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, verbose_name='발행된 글 주소')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='발행 일시')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='articles.analyzedarticle', verbose_name='기사')),
                ('blog_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_articles', to='articles.blogpostingaccount', verbose_name='발행 계정')),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('blog_account', 'article')},
            },
        ),
    ]
