# Generated by Django 5.2.16 on 2026-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_blogpostingaccount_site_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='계정 ID / 블로그 ID'),
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='credential',
            field=models.CharField(blank=True, max_length=255, verbose_name='비밀번호 / API Key / OAuth 리프레시 토큰'),
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='platform',
            field=models.CharField(choices=[('WORDPRESS', '워드프레스'), ('TISTORY', '티스토리'), ('NAVER', '네이버 블로그'), ('BLOGGER', '블로거(Blogger)')], max_length=10, verbose_name='포스팅 플랫폼'),
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='사이트 주소(워드프레스/블로거)'),
        ),
    ]
