# Generated by Django 5.2.16 on 2026-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_blogpostingaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
    ]
