# Generated by Django 5.2.16 on 2026-07-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_userpreference_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='인증 메일 발송 시각'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='이메일 인증 토큰'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='이메일 인증 여부'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='pending_email',
            field=models.CharField(blank=True, max_length=254, verbose_name='인증 대기 중인 이메일'),
        ),
    ]
