# Generated by Django 5.2.16 on 2026-07-11 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_userpreference_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRealtimePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='현재가')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='저가')),
                ('change', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='전일 대비')),
                ('change_pct', models.FloatField(verbose_name='전일 대비율(%)')),
                ('volume', models.BigIntegerField(verbose_name='누적 거래량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_price', to='articles.stockitem', verbose_name='종목')),
            ],
        ),
    ]
