# Generated by Django 5.2.16 on 2026-07-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_stockrealtimeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_method',
            field=models.CharField(choices=[('GENERAL', '일반 로그인'), ('SIGNUP', '회원가입'), ('KAKAO', '카카오'), ('GOOGLE', '구글'), ('NAVER', '네이버')], max_length=10, verbose_name='로그인 방식'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('KAKAO', '카카오톡'), ('GOOGLE', '구글'), ('NAVER', '네이버')], max_length=10, verbose_name='가입 경로'),
        ),
    ]
