# Generated by Django 5.2.16 on 2026-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_loginlog_login_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='구독 활성화 여부')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='구독 신청일')),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
