# Generated by Django 5.2.16 on 2026-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 일시')),
                ('article_count', models.PositiveIntegerField(default=0, verbose_name='포함된 기사 수')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='발송 성공 인원')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
