# Generated by Django 5.2.16 on 2026-07-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_newslettersendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('status', models.CharField(choices=[('DRAFT', '초안(검토 대기)'), ('READY', '발송 대기(다음 자동발송 때 전송)'), ('SENT', '발송 완료')], default='DRAFT', max_length=10, verbose_name='상태')),
                ('article_count', models.PositiveIntegerField(default=0, verbose_name='초안 작성 시 포함된 기사 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='초안 생성일')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 일시')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='발송 성공 인원')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='NewsletterSendLog',
        ),
    ]
