# Generated by Django 5.2.16 on 2026-07-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_newsletterissue_delete_newslettersendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴명')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='URL name(urls.py의 name)')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='직접 URL (url_name이 없을 때 사용)')),
                ('badge_text', models.CharField(blank=True, max_length=20, verbose_name='배지 텍스트 (예: DEMO)')),
                ('menu_type', models.CharField(choices=[('INDEX', '랜딩 페이지(index)'), ('HEADER', '내부 앱 공통 헤더')], max_length=10, verbose_name='노출 화면')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부(숨김 처리)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴 관리',
                'ordering': ['menu_type', 'order', 'id'],
            },
        ),
    ]
