# Generated by Django 5.2.16 on 2026-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_pension_menu_external_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('ISA', 'ISA'), ('IRP', 'IRP'), ('PENSION', '연금저축'), ('INSURANCE', '보험')], max_length=20, verbose_name='상품 유형')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('interest', models.CharField(blank=True, max_length=100, verbose_name='관심 기관/상품')),
                ('goal', models.CharField(blank=True, max_length=200, verbose_name='목표')),
                ('message', models.TextField(blank=True, verbose_name='문의사항')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='접수 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수 일시')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
