# Generated by Django 5.2.16 on 2026-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_consultrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='original_content',
            field=models.TextField(blank=True, default='', verbose_name='원문 본문(스크래핑)'),
        ),
    ]
