# Generated by Django 5.2.16 on 2026-07-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_analyzedarticle_original_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConsultSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, verbose_name='고객 성명')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='고객 연락처')),
                ('consultant_name', models.CharField(blank=True, max_length=50, verbose_name='상담자 (FC/PB)')),
                ('consult_date', models.DateField(blank=True, null=True, verbose_name='상담일자')),
                ('data', models.JSONField(verbose_name='상담 시트 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장 일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자 계정')),
            ],
            options={
                'verbose_name': '재무상담 시트',
                'verbose_name_plural': '재무상담 시트 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
