# Generated by Django 5.2.16 on 2026-07-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_financialconsultsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='등급명')),
                ('level', models.PositiveSmallIntegerField(unique=True, verbose_name='등급 순위(숫자가 클수록 상위 등급)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
            ],
            options={
                'verbose_name': '회원 등급',
                'verbose_name_plural': '회원 등급',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='userpreference',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='articles.membergrade', verbose_name='권한 등급'),
        ),
    ]
