# Generated by Django 5.2.16 on 2026-07-20 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_seed_membergrades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='scraped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_scrapes', to=settings.AUTH_USER_MODEL, verbose_name='수동 스크래핑 등록 회원'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='daily_post_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='일일 포스팅 가능 건수(공란=무제한)'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='daily_scrape_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='일일 스크래핑 가능 건수(공란=무제한)'),
        ),
    ]
