# Generated by Django 5.2.16 on 2026-07-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0040_savings_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='실제 AI 요약 여부'),
        ),
        migrations.AddField(
            model_name='analyzedarticle',
            name='ai_summarized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 요약 실행 일시'),
        ),
        migrations.AddField(
            model_name='analyzedarticle',
            name='ai_summarized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_summarized_articles', to=settings.AUTH_USER_MODEL, verbose_name='AI 요약 실행 회원'),
        ),
        migrations.AddField(
            model_name='membergrade',
            name='daily_ai_summarize_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='일일 AI 요약 가능 건수(공란=무제한)'),
        ),
    ]
