# Generated by Django 5.2.16 on 2026-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_analyzedarticle_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='source_type',
            field=models.CharField(choices=[('RSS', 'RSS 수집 / 회원 직접 등록 (원문 링크 있음)'), ('KIS', 'KIS 종합 시황_공시 (원문 링크 없음)'), ('AI_BRIEFING', 'AI 특징주 통합 브리핑')], default='RSS', max_length=20, verbose_name='수집 소스'),
        ),
    ]
