# Generated by Django 5.2.16 on 2026-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0043_backfill_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedarticle',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', verbose_name='AI 투자 관점 분석'),
        ),
        migrations.AlterField(
            model_name='analyzedarticle',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='AI 3줄 요약'),
        ),
        migrations.AlterField(
            model_name='analyzedarticle',
            name='blog_content',
            field=models.TextField(blank=True, default='', verbose_name='블로그/티스토리 포스팅용 원고'),
        ),
    ]
