# Generated by Django 5.2.16 on 2026-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_backfill_blank_placeholder_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='도메인 (예: mk.co.kr)')),
                ('name', models.CharField(max_length=50, verbose_name='언론사명 (예: 매일경제)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
