# Generated by Django 5.2.16 on 2026-07-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0046_mediaoutlet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedarticle',
            options={'verbose_name': '수집 기사', 'verbose_name_plural': '수집 기사'},
        ),
        migrations.AlterModelOptions(
            name='blogpostingaccount',
            options={'ordering': ['user', 'platform'], 'verbose_name': '블로그 발행 계정', 'verbose_name_plural': '블로그 발행 계정'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '챗봇 대화', 'verbose_name_plural': '챗봇 대화'},
        ),
        migrations.AlterModelOptions(
            name='kisaccesstoken',
            options={'verbose_name': 'KIS 접근 토큰', 'verbose_name_plural': 'KIS 접근 토큰'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-created_at'], 'verbose_name': '로그인 기록', 'verbose_name_plural': '로그인 기록'},
        ),
        migrations.AlterModelOptions(
            name='marketholiday',
            options={'ordering': ['date'], 'verbose_name': '휴장일', 'verbose_name_plural': '휴장일'},
        ),
        migrations.AlterModelOptions(
            name='marketindex',
            options={'ordering': ['-date'], 'verbose_name': '시장 지수', 'verbose_name_plural': '시장 지수'},
        ),
        migrations.AlterModelOptions(
            name='mediaoutlet',
            options={'verbose_name': '언론사 도메인 매핑', 'verbose_name_plural': '언론사 도메인 매핑'},
        ),
        migrations.AlterModelOptions(
            name='menuaccesslog',
            options={'ordering': ['-accessed_at'], 'verbose_name': '메뉴 접속 기록', 'verbose_name_plural': '메뉴 접속 기록'},
        ),
        migrations.AlterModelOptions(
            name='newskeyword',
            options={'verbose_name': '감지 키워드', 'verbose_name_plural': '감지 키워드'},
        ),
        migrations.AlterModelOptions(
            name='newsletterissue',
            options={'ordering': ['-created_at'], 'verbose_name': '뉴스레터 발행', 'verbose_name_plural': '뉴스레터 발행'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': '뉴스레터 구독자', 'verbose_name_plural': '뉴스레터 구독자'},
        ),
        migrations.AlterModelOptions(
            name='newssource',
            options={'verbose_name': 'RSS 언론사', 'verbose_name_plural': 'RSS 언론사'},
        ),
        migrations.AlterModelOptions(
            name='postedarticle',
            options={'ordering': ['-posted_at'], 'verbose_name': '발행 기록', 'verbose_name_plural': '발행 기록'},
        ),
        migrations.AlterModelOptions(
            name='rankedmover',
            options={'ordering': ['rank_type', 'rank'], 'verbose_name': '급등락 순위', 'verbose_name_plural': '급등락 순위'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': '소셜 로그인 계정', 'verbose_name_plural': '소셜 로그인 계정'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': '종목', 'verbose_name_plural': '종목 마스터'},
        ),
        migrations.AlterModelOptions(
            name='stockprediction',
            options={'ordering': ['-date'], 'verbose_name': 'AI 예측', 'verbose_name_plural': 'AI 예측'},
        ),
        migrations.AlterModelOptions(
            name='stockrealtimeprice',
            options={'verbose_name': '실시간 시세', 'verbose_name_plural': '실시간 시세'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': '회원 환경설정', 'verbose_name_plural': '회원 환경설정'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': '프리미엄 구독', 'verbose_name_plural': '프리미엄 구독'},
        ),
    ]
