# Generated by Django 5.2.16 on 2026-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_alter_analyzedarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedarticle',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='발행된 글 주소'),
        ),
    ]
