# Generated by Django 5.2.16 on 2026-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0048_alter_postedarticle_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='platform',
            field=models.CharField(choices=[('WORDPRESS', '워드프레스'), ('BLOGGER', '블로거(Blogger)')], max_length=10, verbose_name='포스팅 플랫폼'),
        ),
    ]
