# Generated by Django 5.2.16 on 2026-07-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0051_rename_news_board_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedarticle',
            options={'verbose_name': '수집 기사 (AnalyzedArticle)', 'verbose_name_plural': '수집 기사 (AnalyzedArticle)'},
        ),
        migrations.AlterModelOptions(
            name='blogpostingaccount',
            options={'ordering': ['user', 'platform'], 'verbose_name': '블로그 발행 계정 (BlogPostingAccount)', 'verbose_name_plural': '블로그 발행 계정 (BlogPostingAccount)'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '챗봇 대화 (ChatMessage)', 'verbose_name_plural': '챗봇 대화 (ChatMessage)'},
        ),
        migrations.AlterModelOptions(
            name='consultrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '상담 신청 (ConsultRequest)', 'verbose_name_plural': '상담 신청 관리 (ConsultRequest)'},
        ),
        migrations.AlterModelOptions(
            name='financialconsultsheet',
            options={'ordering': ['-created_at'], 'verbose_name': '재무상담 시트 (FinancialConsultSheet)', 'verbose_name_plural': '재무상담 시트 관리 (FinancialConsultSheet)'},
        ),
        migrations.AlterModelOptions(
            name='kisaccesstoken',
            options={'verbose_name': 'KIS 접근 토큰 (KisAccessToken)', 'verbose_name_plural': 'KIS 접근 토큰 (KisAccessToken)'},
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-created_at'], 'verbose_name': '로그인 기록 (LoginLog)', 'verbose_name_plural': '로그인 기록 (LoginLog)'},
        ),
        migrations.AlterModelOptions(
            name='marketholiday',
            options={'ordering': ['date'], 'verbose_name': '휴장일 (MarketHoliday)', 'verbose_name_plural': '휴장일 (MarketHoliday)'},
        ),
        migrations.AlterModelOptions(
            name='marketindex',
            options={'ordering': ['-date'], 'verbose_name': '시장 지수 (MarketIndex)', 'verbose_name_plural': '시장 지수 (MarketIndex)'},
        ),
        migrations.AlterModelOptions(
            name='mediaoutlet',
            options={'verbose_name': '언론사 도메인 매핑 (MediaOutlet)', 'verbose_name_plural': '언론사 도메인 매핑 (MediaOutlet)'},
        ),
        migrations.AlterModelOptions(
            name='membergrade',
            options={'ordering': ['level'], 'verbose_name': '회원 등급 (MemberGrade)', 'verbose_name_plural': '회원 등급 (MemberGrade)'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu_type', 'order', 'id'], 'verbose_name': '메뉴 (Menu)', 'verbose_name_plural': '메뉴 관리 (Menu)'},
        ),
        migrations.AlterModelOptions(
            name='menuaccesslog',
            options={'ordering': ['-accessed_at'], 'verbose_name': '메뉴 접속 기록 (MenuAccessLog)', 'verbose_name_plural': '메뉴 접속 기록 (MenuAccessLog)'},
        ),
        migrations.AlterModelOptions(
            name='newskeyword',
            options={'verbose_name': '감지 키워드 (NewsKeyword)', 'verbose_name_plural': '감지 키워드 (NewsKeyword)'},
        ),
        migrations.AlterModelOptions(
            name='newsletterissue',
            options={'ordering': ['-created_at'], 'verbose_name': '뉴스레터 발행 (NewsletterIssue)', 'verbose_name_plural': '뉴스레터 발행 (NewsletterIssue)'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': '뉴스레터 구독자 (NewsletterSubscriber)', 'verbose_name_plural': '뉴스레터 구독자 (NewsletterSubscriber)'},
        ),
        migrations.AlterModelOptions(
            name='newssource',
            options={'verbose_name': 'RSS 언론사 (NewsSource)', 'verbose_name_plural': 'RSS 언론사 (NewsSource)'},
        ),
        migrations.AlterModelOptions(
            name='postedarticle',
            options={'ordering': ['-posted_at'], 'verbose_name': '발행 기록 (PostedArticle)', 'verbose_name_plural': '발행 기록 (PostedArticle)'},
        ),
        migrations.AlterModelOptions(
            name='rankedmover',
            options={'ordering': ['rank_type', 'rank'], 'verbose_name': '급등락 순위 (RankedMover)', 'verbose_name_plural': '급등락 순위 (RankedMover)'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': '소셜 로그인 계정 (SocialAccount)', 'verbose_name_plural': '소셜 로그인 계정 (SocialAccount)'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': '종목 (StockItem)', 'verbose_name_plural': '종목 마스터 (StockItem)'},
        ),
        migrations.AlterModelOptions(
            name='stockprediction',
            options={'ordering': ['-date'], 'verbose_name': 'AI 예측 (StockPrediction)', 'verbose_name_plural': 'AI 예측 (StockPrediction)'},
        ),
        migrations.AlterModelOptions(
            name='stockrealtimeprice',
            options={'verbose_name': '실시간 시세 (StockRealtimePrice)', 'verbose_name_plural': '실시간 시세 (StockRealtimePrice)'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': '회원 환경설정 (UserPreference)', 'verbose_name_plural': '회원 환경설정 (UserPreference)'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': '프리미엄 구독 (UserSubscription)', 'verbose_name_plural': '프리미엄 구독 (UserSubscription)'},
        ),
    ]
