# Generated by Django 5.2.16 on 2026-07-29 10:24, then hand-edited.
#
# StockPrediction이 실가격(OHLCV)과 AI 예측값을 한 테이블에 같이 담고 있어 혼란을 줘서
# (90만+ 행 중 예측값이 채워진 건 0.1%도 안 됨), 실가격은 새 StockDailyPrice로 분리한다.
#
# makemigrations가 자동 생성한 순서(RemoveField가 CreateModel보다 먼저)는 그대로 실행하면
# 새 테이블이 생기기도 전에 기존 90만+ 행의 가격 컬럼을 지워버려 데이터가 통째로 날아간다.
# 그래서 순서를 CreateModel → 데이터 복사(RunPython, raw SQL) → RemoveField로 수동 재배치했다.
# 이 서버는 RAM이 1GB가 안 돼 OOM 이력이 있는 서버라, 90만+ 행을 Django ORM으로 한 줄씩
# 옮기지 않고 MySQL이 서버 쪽에서 셋 기반으로 처리하는 INSERT...SELECT를 그대로 쓴다.

import django.db.models.deletion
from django.db import migrations, models


def copy_prices_forward(apps, schema_editor):
    """StockPrediction의 가격 컬럼을 StockDailyPrice로 복사한다. 대상 테이블이 비어있을 때만
    복사하고(재실행/부분실패 대비), 복사 후 행 수가 원본과 다르면 그대로 실패시켜 뒤이은
    RemoveField가 데이터를 지우지 못하게 막는다."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM articles_stockdailyprice")
        (already_copied,) = cursor.fetchone()
        if already_copied:
            return  # 이미 복사됐으면(재실행 등) 다시 복사하지 않는다

        cursor.execute("SELECT COUNT(*) FROM articles_stockprediction")
        (source_count,) = cursor.fetchone()

        cursor.execute("""
            INSERT INTO articles_stockdailyprice
                (stock_id, date, open_price, high_price, low_price, close_price, volume, trading_amount)
            SELECT stock_id, date, open_price, high_price, low_price, close_price, volume, trading_amount
            FROM articles_stockprediction
        """)

        cursor.execute("SELECT COUNT(*) FROM articles_stockdailyprice")
        (copied_count,) = cursor.fetchone()
        if copied_count != source_count:
            raise RuntimeError(
                f"가격 데이터 복사 건수 불일치: 원본 {source_count}건, 복사됨 {copied_count}건. "
                "안전을 위해 마이그레이션을 중단합니다(뒤이은 RemoveField가 실행되지 않음)."
            )


def copy_prices_backward(apps, schema_editor):
    """되돌릴 때는 StockDailyPrice를 비우기만 한다 — StockPrediction 쪽 가격 컬럼은
    이 마이그레이션의 RemoveField가 이미 되돌리며(AddField) 원복하므로 여기선 건드리지 않는다."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DELETE FROM articles_stockdailyprice")


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0052_alter_analyzedarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='시가')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='고가')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='저가')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('trading_amount', models.BigIntegerField(blank=True, null=True, verbose_name='거래금액')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='articles.stockitem', verbose_name='종목')),
            ],
            options={
                'verbose_name': '일별 시세 (StockDailyPrice)',
                'verbose_name_plural': '일별 시세 (StockDailyPrice)',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'stock', '-id'], name='dailyprice_date_stock_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.RunPython(copy_prices_forward, copy_prices_backward),
        migrations.RemoveField(
            model_name='stockprediction',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='trading_amount',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='volume',
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='date',
            field=models.DateField(verbose_name='예측 기준일(이 날짜 종가까지의 데이터로 다음날을 예측)'),
        ),
    ]
