# Generated by Django 5.2.16 on 2026-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_remove_stockprediction_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrequest',
            name='product',
            field=models.CharField(choices=[('ISA', 'ISA'), ('IRP', 'IRP'), ('PENSION', '연금저축'), ('INSURANCE', '보험'), ('ASSET', '자산관리 종합')], max_length=20, verbose_name='상품 유형'),
        ),
    ]
