# Generated by Django 5.2.16 on 2026-07-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_remove_stockprediction_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='has_reuse_restriction',
            field=models.BooleanField(default=False, verbose_name='원문 재사용 제한 문구 감지'),
        ),
    ]
