# Generated by Django 5.2.16 on 2026-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0054_analyzedarticle_has_reuse_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/', verbose_name='발행용 썸네일'),
        ),
    ]
