# Generated by Django 5.2.16 on 2026-07-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0055_analyzedarticle_thumbnail'),
        ('articles', '0055_seed_expert_consult_menu'),
    ]

    operations = [
    ]
