# Generated by Django 5.2.16 on 2026-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0056_merge_20260730_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='거래량'),
        ),
    ]
