# Generated by Django 5.2.16 on 2026-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_marketindex_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='foreign_net_qty',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='외국인 순매수 수량'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='institution_net_qty',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='기관계 순매수 수량'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='retail_net_qty',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='개인 순매수 수량'),
        ),
    ]
