# Generated by Django 5.2.16 on 2026-08-03 21:52

import articles.fields
from django.db import migrations


def encrypt_existing_credentials(apps, schema_editor):
    """AlterField 직후 시점엔 아직 credential이 평문 그대로 DB에 있으므로, 한 번씩
    다시 저장(save)해서 EncryptedCharField.get_prep_value()로 암호화 처리한다."""
    BlogPostingAccount = apps.get_model('articles', 'BlogPostingAccount')
    for account in BlogPostingAccount.objects.exclude(credential=''):
        account.save(update_fields=['credential'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_marketindex_foreign_net_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='credential',
            field=articles.fields.EncryptedCharField(blank=True, max_length=1024, verbose_name='비밀번호 / API Key / OAuth 리프레시 토큰'),
        ),
        migrations.RunPython(encrypt_existing_credentials, noop_reverse),
    ]
