# Generated by Django 5.2.16 on 2026-08-04 01:04

from django.db import migrations, models

# _header.html에 정적 JS 배열로 먼저 넣어봤던 큐레이션 목록을 그대로 초기 데이터로 옮긴다.
INITIAL_KEYWORDS = [
    'AI', '인공지능', '머신러닝', '딥러닝', 'LightGBM', 'RandomForest', '앙상블모델',
    '주가예측', '매매신호', '실시간시세', '등락률순위', '특징주브리핑', '기술적지표',
    '코스피', '코스닥', '주식시장', '환율', '금리', '증권사리포트', '투자',
    '자산관리', '재테크', '포트폴리오', '뉴스분석', '빅데이터', '자동화',
    '챗봇', '블로그자동발행', '뉴스레터', '종목분석',
]


def seed_initial_keywords(apps, schema_editor):
    TickerKeyword = apps.get_model('articles', 'TickerKeyword')
    TickerKeyword.objects.bulk_create([
        TickerKeyword(keyword=kw, order=i) for i, kw in enumerate(INITIAL_KEYWORDS)
    ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0059_encrypt_blogpostingaccount_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='키워드')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부(숨김 처리)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '키워드 티커 (TickerKeyword)',
                'verbose_name_plural': '키워드 티커 관리 (TickerKeyword)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_initial_keywords, noop_reverse),
    ]
