# Generated by Django 5.2.16 on 2026-08-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0060_add_ticker_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerKeyword',
        ),
    ]
