# Generated by Django 5.2.16 on 2026-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0061_remove_ticker_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMarketQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOREIGN_INDEX', '해외지수'), ('FX_RATE', '국제 시장 환율'), ('INTEREST_RATE', '금리')], max_length=20, verbose_name='구분')),
                ('code', models.CharField(max_length=20, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='현재가')),
                ('change_pct', models.FloatField(verbose_name='전일 대비율(%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
            ],
            options={
                'verbose_name': '해외지수/환율/금리 (GlobalMarketQuote)',
                'verbose_name_plural': '해외지수/환율/금리 (GlobalMarketQuote)',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
