# Generated by Django 5.2.16 on 2026-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0062_add_global_market_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmarketquote',
            name='category',
            field=models.CharField(choices=[('FOREIGN_INDEX', '해외지수'), ('FX_RATE', '국제 시장 환율'), ('FX_FIXING', '환전 고시 환율'), ('INTEREST_RATE', '금리')], max_length=20, verbose_name='구분'),
        ),
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=20, verbose_name='통화 코드')),
                ('currency_name', models.CharField(max_length=50, verbose_name='통화명')),
                ('date', models.DateField(verbose_name='고시 일자')),
                ('deal_bas_r', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='매매기준율')),
            ],
            options={
                'verbose_name': '환전 고시 환율 이력 (ExchangeRateSnapshot)',
                'verbose_name_plural': '환전 고시 환율 이력 (ExchangeRateSnapshot)',
                'ordering': ['currency_code', '-date'],
                'unique_together': {('currency_code', 'date')},
            },
        ),
    ]
