# Generated by Django 5.2.16 on 2026-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0063_add_exchange_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedmover',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='전일 대비 금액(원, 부호 포함)'),
        ),
    ]
