# Generated by Django 5.2.16 on 2026-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0064_add_rankedmover_change_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedarticle',
            name='source_type',
            field=models.CharField(choices=[('RSS', 'RSS 수집 / 회원 URL 등록 (원문 링크 있음)'), ('KIS', 'KIS 종합 시황_공시 (원문 링크 없음)'), ('AI_BRIEFING', 'AI 특징주 통합 브리핑'), ('MANUAL', '회원 직접 작성 (원문 링크 없음)')], default='RSS', max_length=20, verbose_name='수집 소스'),
        ),
    ]
