# Generated by Django 5.2.16 on 2026-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0065_alter_analyzedarticle_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedarticle',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='발행된 글 ID(플랫폼 내부)'),
        ),
        migrations.AddField(
            model_name='postedarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최근 재발행 일시'),
        ),
    ]
