# Generated by Django 5.2.16 on 2026-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0066_postedarticle_external_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='foreign_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='외국인 순매수 금액(억원)'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='institution_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='기관계 순매수 금액(억원)'),
        ),
        migrations.AddField(
            model_name='marketindex',
            name='retail_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='개인 순매수 금액(억원)'),
        ),
    ]
