# Generated by Django 5.2.16 on 2026-08-04 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0068_rename_expert_consult_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='구독자명')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대전화번호')),
                ('referral_source', models.CharField(blank=True, choices=[('SEARCH', '포털 검색'), ('SNS', 'SNS'), ('FRIEND', '지인 추천'), ('NEWSLETTER', 'NextFinUp 뉴스레터'), ('OTHER', '기타')], max_length=20, verbose_name='가입 경로')),
                ('motivation', models.CharField(blank=True, choices=[('INFO', '투자·재테크 정보 습득'), ('EXPERT', '전문가 상담 연계'), ('CONTENT', '프리미엄 콘텐츠 이용'), ('OTHER', '기타')], max_length=20, verbose_name='구독 동기')),
                ('payment_method', models.CharField(choices=[('KAKAOPAY', '카카오페이'), ('NAVERPAY', '네이버페이'), ('CARD', '신용카드')], max_length=10, verbose_name='결제 수단')),
                ('status', models.CharField(choices=[('PENDING', '검토 대기'), ('APPROVED', '승인 완료'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구독 신청 (SubscriptionOrder)',
                'verbose_name_plural': '구독 신청 관리 (SubscriptionOrder)',
                'ordering': ['-created_at'],
            },
        ),
    ]
