# Generated by Django 5.2.16 on 2026-08-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0071_default_ai_summarize_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInvestorFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('foreign_net_qty', models.BigIntegerField(verbose_name='외국인 순매수 수량')),
                ('foreign_net_amount', models.BigIntegerField(verbose_name='외국인 순매수 금액(백만원)')),
                ('retail_net_qty', models.BigIntegerField(verbose_name='개인 순매수 수량')),
                ('retail_net_amount', models.BigIntegerField(verbose_name='개인 순매수 금액(백만원)')),
                ('institution_net_qty', models.BigIntegerField(verbose_name='기관계 순매수 수량')),
                ('institution_net_amount', models.BigIntegerField(verbose_name='기관계 순매수 금액(백만원)')),
                ('pension_net_qty', models.BigIntegerField(verbose_name='기금(연기금류) 순매수 수량')),
                ('pension_net_amount', models.BigIntegerField(verbose_name='기금(연기금류) 순매수 금액(백만원)')),
                ('trust_net_qty', models.BigIntegerField(verbose_name='투자신탁 순매수 수량')),
                ('trust_net_amount', models.BigIntegerField(verbose_name='투자신탁 순매수 금액(백만원)')),
                ('pe_fund_net_qty', models.BigIntegerField(verbose_name='사모펀드 순매수 수량')),
                ('pe_fund_net_amount', models.BigIntegerField(verbose_name='사모펀드 순매수 금액(백만원)')),
                ('securities_net_qty', models.BigIntegerField(verbose_name='증권 순매수 수량')),
                ('securities_net_amount', models.BigIntegerField(verbose_name='증권 순매수 금액(백만원)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_flows', to='articles.stockitem', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목별 투자자 수급 (StockInvestorFlow)',
                'verbose_name_plural': '종목별 투자자 수급 (StockInvestorFlow)',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'stock', '-id'], name='investorflow_date_stock_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
