# Generated by Django 5.2.16 on 2026-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0072_stockinvestorflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='payment_method',
            field=models.CharField(choices=[('KAKAOPAY', '카카오페이'), ('NAVERPAY', '네이버페이'), ('CARD', '신용카드'), ('TRANSFER', '계좌이체')], max_length=10, verbose_name='결제 수단'),
        ),
    ]
