# Generated by Django 5.2.16 on 2026-08-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0073_alter_subscriptionorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprediction',
            name='down_probability_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='하락 확률(수급 반영)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='holdout_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='검증 정확도(기본 피처)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='holdout_accuracy_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='검증 정확도(수급 반영)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='pred_5day_return_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='AI 향후 5일 예상수익률(수급 반영)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='pred_next_close_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='AI 내일 예상종가(수급 반영)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='trading_signal_flow',
            field=models.CharField(blank=True, choices=[('BUY', '매수'), ('SELL', '매도'), ('HOLD', '관망')], max_length=5, null=True, verbose_name='매매 신호(수급 반영)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='up_probability_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='상승 확률(수급 반영)'),
        ),
    ]
