# Generated by Django 5.2.16 on 2026-08-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0074_stockprediction_down_probability_flow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('stock_code', models.CharField(blank=True, max_length=6, verbose_name='종목코드')),
                ('corp_cls', models.CharField(blank=True, max_length=1, verbose_name='법인구분(Y/K/N/E)')),
                ('report_nm', models.CharField(max_length=500, verbose_name='보고서명')),
                ('rcept_no', models.CharField(max_length=14, unique=True, verbose_name='접수번호')),
                ('rcept_dt', models.DateField(verbose_name='접수일자')),
                ('pblntf_ty', models.CharField(choices=[('A', '정기공시'), ('B', '주요사항보고'), ('C', '발행공시'), ('D', '지분공시'), ('E', '기타공시'), ('F', '외부감사관련'), ('G', '펀드공시'), ('H', '자산유동화'), ('I', '거래소공시'), ('J', '공정위공시')], max_length=1, verbose_name='공시유형')),
                ('pblntf_detail_ty', models.CharField(blank=True, max_length=10, verbose_name='공시상세유형')),
                ('flr_nm', models.CharField(blank=True, max_length=100, verbose_name='제출인명')),
                ('rm', models.CharField(blank=True, max_length=20, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, help_text='종목코드가 StockItem과 매칭되는 경우만 연결 (미상장/코넥스 등은 NULL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='articles.stockitem', verbose_name='종목')),
            ],
            options={
                'verbose_name': '종목 공시 (StockDisclosure)',
                'verbose_name_plural': '종목 공시 (StockDisclosure)',
                'ordering': ['-rcept_dt', '-rcept_no'],
                'indexes': [models.Index(fields=['-rcept_dt', 'stock'], name='disclosure_date_stock_idx')],
            },
        ),
    ]
