# Generated by Django 5.2.16 on 2026-08-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0075_stockdisclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedarticle',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', verbose_name='AI 관점 분석'),
        ),
    ]
