# Generated by Django 5.2.16 on 2026-08-07 16:03

import articles.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0076_alter_analyzedarticle_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostingaccount',
            name='oauth_token_secret',
            field=articles.fields.EncryptedCharField(blank=True, max_length=1024, verbose_name='OAuth 토큰 시크릿(텀블러 전용)'),
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='credential',
            field=articles.fields.EncryptedCharField(blank=True, max_length=1024, verbose_name='비밀번호 / API Key / OAuth 토큰'),
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='platform',
            field=models.CharField(choices=[('WORDPRESS', '워드프레스'), ('BLOGGER', '블로거(Blogger)'), ('TUMBLR', '텀블러(Tumblr)')], max_length=10, verbose_name='포스팅 플랫폼'),
        ),
    ]
