# Generated by Django 5.2.16 on 2026-08-07 16:28

import articles.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0077_blogpostingaccount_oauth_token_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostingaccount',
            name='oauth_token_secret',
        ),
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='credential',
            field=articles.fields.EncryptedCharField(blank=True, max_length=1024, verbose_name='비밀번호 / API Key / OAuth 리프레시 토큰'),
        ),
    ]
