# Generated by Django 5.2.16 on 2026-08-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0078_remove_blogpostingaccount_oauth_token_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='bps',
            field=models.FloatField(blank=True, null=True, verbose_name='BPS'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='eps',
            field=models.FloatField(blank=True, null=True, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='시가총액(원)'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='pbr',
            field=models.FloatField(blank=True, null=True, verbose_name='PBR'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='per',
            field=models.FloatField(blank=True, null=True, verbose_name='PER'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='week52_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='52주 최고가'),
        ),
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='week52_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='52주 최저가'),
        ),
    ]
