# Generated by Django 5.2.16 on 2026-08-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0080_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAccuracySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='계산 시각')),
                ('total_resolved', models.IntegerField(verbose_name='결과 확정된 예측 수(신뢰도 무관 전체)')),
                ('overall_accuracy', models.FloatField(verbose_name='전체 방향성 정확도(신뢰도 무관)')),
                ('buckets', models.JSONField(verbose_name='신뢰도 구간별 누적 정확도')),
            ],
            options={
                'verbose_name': 'AI 예측 정확도 스냅샷 (PredictionAccuracySnapshot)',
                'verbose_name_plural': 'AI 예측 정확도 스냅샷 (PredictionAccuracySnapshot)',
                'ordering': ['-computed_at'],
            },
        ),
    ]
