# Generated by Django 5.2.16 on 2026-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0081_predictionaccuracysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCOUNT', '회원/계정'), ('SUBSCRIPTION', '구독/이용권'), ('PREDICTION', 'AI 예측'), ('BLOG', '블로그 자동 발행'), ('NEWSLETTER', '뉴스레터'), ('ETC', '기타')], default='ETC', max_length=20, verbose_name='분류')),
                ('question', models.CharField(max_length=200, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ 관리 (Faq)',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
