# Generated by Django 5.2.16 on 2026-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0082_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='temp_password_active',
            field=models.BooleanField(default=False, verbose_name='임시 비밀번호 사용 중'),
        ),
    ]
