# Generated by Django 5.2.16 on 2026-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0083_userpreference_temp_password_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='CSS 변수명 (예: --brand-primary)')),
                ('value', models.CharField(max_length=20, verbose_name='색상값 (예: #0d47a1)')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='설명')),
                ('group', models.CharField(choices=[('BRAND', '브랜드 블루'), ('BG', '배경'), ('TEXT', '텍스트'), ('BORDER', '테두리'), ('DANGER', '위험/오류'), ('SUCCESS', '성공'), ('OTHER', '경고/기타')], default='OTHER', max_length=10, verbose_name='분류')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '테마 색상 (ThemeColor)',
                'verbose_name_plural': '테마 색상 관리 (ThemeColor)',
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
