# Generated by Django 5.2.16 on 2026-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0085_seed_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='ai_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='AI 가공 제목'),
        ),
    ]
