# Generated by Django 5.2.16 on 2026-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0086_analyzedarticle_ai_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='ERROR', max_length=10, verbose_name='심각도')),
                ('logger_name', models.CharField(max_length=100, verbose_name='로거 이름')),
                ('message', models.TextField(verbose_name='메시지')),
                ('traceback', models.TextField(blank=True, verbose_name='트레이스백')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='요청 경로')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='요청 메서드')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='상태 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시각')),
            ],
            options={
                'verbose_name': '시스템 에러 로그',
                'verbose_name_plural': '시스템 에러 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='articles_sy_created_be3ff5_idx')],
            },
        ),
    ]
