# Generated by Django 5.2.16 on 2026-08-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0087_systemerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedarticle',
            name='content_category',
            field=models.CharField(choices=[('ECONOMY', '경제'), ('HEALTH', '건강/의학')], default='ECONOMY', max_length=10, verbose_name='콘텐츠 카테고리'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='news_subscription',
            field=models.CharField(choices=[('ECONOMY', '경제'), ('HEALTH', '건강/의학')], default='ECONOMY', max_length=10, verbose_name='구독 카테고리'),
        ),
    ]
