# Generated by Django 5.2.16 on 2026-08-21 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0089_alter_analyzedarticle_content_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('model_name', models.CharField(max_length=30, verbose_name='모델')),
                ('size', models.CharField(max_length=30, verbose_name='해상도')),
                ('quality', models.CharField(max_length=20, verbose_name='품질')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('file_path', models.CharField(max_length=255, verbose_name='저장 경로 (media 기준 상대경로)')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='추정 비용(USD)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성한 관리자')),
            ],
            options={
                'verbose_name': 'AI 이미지 생성 기록 (GeneratedImage)',
                'verbose_name_plural': 'AI 이미지 생성 기록 (GeneratedImage)',
                'ordering': ['-created_at'],
            },
        ),
    ]
