# Generated by Django 5.2.16 on 2026-08-27 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0092_utools_menu_points_to_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('stored_filename', models.CharField(max_length=255, unique=True, verbose_name='저장 파일명')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='파일 크기(바이트)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 관리자')),
            ],
            options={
                'verbose_name': '관리자 업로드 파일 (AdminUpload)',
                'verbose_name_plural': '관리자 업로드 파일 (AdminUpload)',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
