# Generated by Django 5.2.16 on 2026-08-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0093_adminupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedarticle',
            name='content_category',
            field=models.CharField(choices=[('ECONOMY', '경제'), ('HEALTH', '건강/의학'), ('FOOD', '음식/영양'), ('TRAVEL', '여행/관광')], default='ECONOMY', max_length=10, verbose_name='콘텐츠 카테고리'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='news_subscription',
            field=models.CharField(choices=[('ECONOMY', '경제'), ('HEALTH', '건강/의학'), ('FOOD', '음식/영양'), ('TRAVEL', '여행/관광')], default='ECONOMY', max_length=10, verbose_name='구독 카테고리'),
        ),
        migrations.CreateModel(
            name='ContentCalendarTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HEALTH', '건강/의학'), ('FOOD', '음식/영양'), ('TRAVEL', '여행/관광')], max_length=20, verbose_name='카테고리')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='요일(0=월 ~ 6=일)')),
                ('key', models.CharField(max_length=50, verbose_name='내부 식별자')),
                ('name', models.CharField(max_length=100, verbose_name='테마명')),
                ('am_angle', models.CharField(max_length=200, verbose_name='오전 각도 라벨')),
                ('pm_angle', models.CharField(max_length=200, verbose_name='오후 각도 라벨')),
                ('am_title_template', models.CharField(max_length=200, verbose_name='오전 제목 템플릿({t}에 주제 삽입)')),
                ('pm_title_template', models.CharField(max_length=200, verbose_name='오후 제목 템플릿({t}에 주제 삽입)')),
            ],
            options={
                'verbose_name': '캘린더 요일 테마 (ContentCalendarTheme)',
                'verbose_name_plural': '캘린더 요일 테마 관리 (ContentCalendarTheme)',
                'ordering': ['category', 'weekday'],
                'unique_together': {('category', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='ContentCalendarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HEALTH', '건강/의학'), ('FOOD', '음식/영양'), ('TRAVEL', '여행/관광')], max_length=20, verbose_name='카테고리')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='요일(0=월 ~ 6=일)')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='주차(0~51)')),
                ('topic', models.CharField(max_length=255, verbose_name='주제')),
            ],
            options={
                'verbose_name': '캘린더 주제 (ContentCalendarTopic)',
                'verbose_name_plural': '캘린더 주제 관리 (ContentCalendarTopic)',
                'ordering': ['category', 'weekday', 'week_number'],
                'unique_together': {('category', 'weekday', 'week_number')},
            },
        ),
    ]
