# Generated by Django 5.2.16 on 2026-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0094_alter_analyzedarticle_content_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostingaccount',
            name='platform',
            field=models.CharField(choices=[('WORDPRESS', '워드프레스'), ('BLOGGER', '블로거(Blogger)')], max_length=10, verbose_name='포스팅 플랫폼'),
        ),
    ]
