# Generated by Django 5.2.16 on 2026-09-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0095_alter_blogpostingaccount_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='source_size',
            field=models.CharField(blank=True, max_length=20, verbose_name='원본 해상도'),
        ),
    ]
