# Generated by Django 5.2.16 on 2026-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0096_generatedimage_source_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='입력 토큰'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='출력 토큰'),
        ),
    ]
