# Generated by Django 5.2.16 on 2026-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0097_generatedimage_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='series_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='시리즈 내 순번'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='series_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='시리즈 키'),
        ),
    ]
