# Generated by Django 5.2.16 on 2026-09-08 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0098_generatedimage_series_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(db_index=True, max_length=100, verbose_name='네이버 블로그 ID')),
                ('log_no', models.CharField(max_length=30, verbose_name='네이버 글 번호(logNo)')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('content_html', models.TextField(blank=True, verbose_name='본문 HTML (이미지 재호스팅 완료)')),
                ('original_content_html', models.TextField(blank=True, verbose_name='본문 HTML (네이버 원본)')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='본문 요약(목록 표시용)')),
                ('category_name', models.CharField(blank=True, max_length=100, verbose_name='네이버 카테고리')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='태그(쉼표 구분)')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='네이버 원문 작성일')),
                ('source_url', models.URLField(max_length=500, verbose_name='네이버 원문 URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='대표 이미지 URL(재호스팅본)')),
                ('image_map', models.JSONField(blank=True, default=dict, verbose_name='이미지 매핑(원본→재호스팅)')),
                ('image_count', models.PositiveIntegerField(default=0, verbose_name='본문 이미지 수')),
                ('status', models.CharField(choices=[('LISTED', '목록만 수집(본문 없음)'), ('SCRAPED', '본문 수집 완료'), ('FAILED', '수집 실패')], db_index=True, default='LISTED', max_length=10, verbose_name='수집 상태')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='마지막 수집 오류')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='본문 수집 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naver_blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='소유 회원')),
            ],
            options={
                'verbose_name': '네이버 블로그 원문 (NaverBlogPost)',
                'verbose_name_plural': '네이버 블로그 원문 (NaverBlogPost)',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NaverPostMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', '발행 성공'), ('FAILED', '발행 실패')], default='SUCCESS', max_length=10, verbose_name='발행 결과')),
                ('target_post_id', models.CharField(blank=True, max_length=100, verbose_name='대상 플랫폼 글 ID')),
                ('target_url', models.URLField(blank=True, max_length=500, verbose_name='발행된 글 URL')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='실패 사유')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 생성일')),
                ('blog_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naver_migrations', to='articles.blogpostingaccount', verbose_name='발행 대상 블로그 계정')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='articles.naverblogpost', verbose_name='네이버 원문')),
            ],
            options={
                'verbose_name': '네이버 글 이관 기록 (NaverPostMigration)',
                'verbose_name_plural': '네이버 글 이관 기록 (NaverPostMigration)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='naverblogpost',
            index=models.Index(fields=['blog_id', 'status'], name='articles_na_blog_id_f28cf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='naverblogpost',
            unique_together={('blog_id', 'log_no')},
        ),
        migrations.AlterUniqueTogether(
            name='naverpostmigration',
            unique_together={('post', 'blog_account')},
        ),
    ]
