# Generated by Django 5.2.16 on 2026-09-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0099_naverblogpost_naverpostmigration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostingaccount',
            name='daily_post_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='하루 발행 한도(공란=권장값, 0=무제한)'),
        ),
    ]
