# Generated by Django 5.2.16 on 2026-09-17 12:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0100_blogpostingaccount_daily_post_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_chat_limit', models.PositiveIntegerField(default=100, help_text='로그인 회원은 계정별, 비로그인은 세션별·IP별로 오늘(한국 시간) 질문 수를 센다. 0이면 무제한. 스태프 계정은 한도 없음.', verbose_name='일일 질문 가능 건수(로그인/세션/IP 공통 한도)')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='예: gpt-4o-mini, gpt-4o. OpenAI가 모델을 추가/폐기해도 여기 값만 바꾸면 됨.', max_length=50, verbose_name='OpenAI 모델명')),
                ('max_tokens', models.PositiveIntegerField(default=500, help_text='너무 크게 잡으면 답변 1건당 비용/응답시간이 늘어남.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(4000)], verbose_name='답변 최대 토큰 수')),
                ('temperature', models.FloatField(default=0.3, help_text='낮을수록 사실 기반으로 딱딱하게, 높을수록 다양하고 자유롭게 답변.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='temperature(창의성, 0~2)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '챗봇 설정',
                'verbose_name_plural': '챗봇 설정',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='접속 IP(일일 한도 IP 기준 집계용)'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['ip_address', 'created_at'], name='articles_chatmsg_ip_idx'),
        ),
    ]
