"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 비밀번호/API 키 등 민감 정보는 .env 파일(git에는 커밋되지 않음)에서 읽어옵니다.
# 필요한 키 목록은 .env.example 참고.
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# .env(또는 서버 환경변수)에 DEBUG를 명시하지 않으면 기본값은 False(운영 안전 기본값)로 동작합니다.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['nextfinup.com', 'www.nextfinup.com', 'admin.nextfinup.com', 'localhost', '127.0.0.1', '168.110.100.189', '134.185.118.175', '10.0.0.2']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'articles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'articles.middleware.KSTMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'articles.middleware.MenuAccessLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # BASE_DIR/templates가 앱별 템플릿(APP_DIRS)보다 먼저 검색되므로, 여기 있는
        # admin/index.html이 django.contrib.admin이 제공하는 기본 템플릿을 오버라이드한다.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'articles.context_processors.menu_items',
                'articles.context_processors.theme_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'nextfinup_db'),
        'USER': os.environ.get('DB_USER', 'nextfinup_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # MySQL의 skip_name_resolve가 꺼져 있어 신규 연결마다 역DNS 조회로 ~1초가 걸린다.
        # CONN_MAX_AGE로 워커 프로세스 안에서 커넥션을 재사용해 매 요청마다 새로 맺지 않게 한다.
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# 기본 'error' 태그는 부트스트랩에 대응하는 alert-error 클래스가 없어(alert-danger만 존재),
# 템플릿에서 alert-{{ message.tags }}로 그리면 스타일이 안 먹으므로 danger로 맞춰준다.
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic 결과물 (nginx가 이 경로를 직접 서빙)

# 기사별 AI 요약 썸네일(articles/thumbnail.py) 등 요청 시점에 생성되는 미디어 파일용.
# nginx가 /media/를 이 경로에서 직접 서빙한다 (STATIC_ROOT와 동일한 패턴).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Nginx 리버스 프록시 환경에서 HTTPS 도메인 요청을 안전하게 허용합니다.
CSRF_TRUSTED_ORIGINS = [
    'https://nextfinup.com',
    'https://www.nextfinup.com',
    'https://admin.nextfinup.com',
]

# 관리 커맨드(cron)처럼 request 객체가 없는 곳에서 절대 URL(예: 뉴스레터 수신거부 링크)을 만들 때 사용
SITE_URL = 'https://www.nextfinup.com'

# 로그인/로그아웃 후 이동할 기본 경로
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# 기본 ModelBackend는 is_active=False 계정을 authenticate() 단계에서 조용히 걸러버려서,
# LoginForm.confirm_login_allowed()가 아예 호출되지 않고 "아이디/비밀번호가 틀렸습니다" 같은
# 부정확한 에러만 뜬다. 이메일 미인증 계정에 정확한 안내 메시지를 보여주기 위해, 활성 여부
# 판단을 폼(confirm_login_allowed)에 위임하는 공식 백엔드로 교체한다.
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# 카카오/구글 소셜 로그인 연동 키 (각 개발자 콘솔에서 발급받아 실제 값으로 교체하세요)
# - 카카오: https://developers.kakao.com  (내 애플리케이션 > 앱 키 > REST API 키)
#   앱 ID: 1508186
#   허용 Redirect URI: https://nextfinup.com/accounts/kakao/callback/
# - 구글: https://console.cloud.google.com/apis/credentials
#   허용 Redirect URI: https://nextfinup.com/accounts/google/callback/
KAKAO_CLIENT_ID = os.environ.get('KAKAO_CLIENT_ID')
KAKAO_CLIENT_SECRET = os.environ.get('KAKAO_CLIENT_SECRET')

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

# - 네이버: https://developers.naver.com/apps  (애플리케이션 > API 설정)
#   서비스 URL: https://www.nextfinup.com
#   허용 Callback URL: https://www.nextfinup.com/api/member/oauth2c
NAVER_CLIENT_ID = os.environ.get('NAVER_CLIENT_ID')
NAVER_CLIENT_SECRET = os.environ.get('NAVER_CLIENT_SECRET')

# - 텀블러(마이페이지 자동 포스팅 연동, 로그인용 아님): https://www.tumblr.com/oauth/apps
#   Consumer Key/Secret 발급 시 Callback URL을 https://www.nextfinup.com/accounts/tumblr/callback/ 로 등록
TUMBLR_CONSUMER_KEY = os.environ.get('TUMBLR_CONSUMER_KEY')
TUMBLR_CONSUMER_SECRET = os.environ.get('TUMBLR_CONSUMER_SECRET')

# 챗봇용 OpenAI API 키 (실제 키로 교체 전까지는 시뮬레이션 모드로 동작 - articles/chatbot_client.py 참고)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', 'YOUR_OPENAI_API_KEY_HERE')

# 기사 AI 3줄 요약/투자 분석/블로그 초안 생성용 Gemini API 키 (실제 키로 교체 전까지는 시뮬레이션
# 모드로 동작 - articles/article_ai.py 참고). Google AI Studio에서 무료로 발급받을 수 있다.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'YOUR_GEMINI_API_KEY_HERE')

# 한국투자증권(KIS) Open API - 실전투자(실계좌) 앱 키
# https://apiportal.koreainvestment.com
KIS_APP_KEY = os.environ.get('KIS_APP_KEY')
KIS_APP_SECRET = os.environ.get('KIS_APP_SECRET')

# BlogPostingAccount.credential(비밀번호/OAuth 리프레시 토큰) 암호화용 Fernet 키
# (articles/fields.py의 EncryptedCharField 참고). 분실 시 기존 저장된 credential을 복호화할
# 수 없게 되므로 안전하게 백업해둘 것.
CREDENTIAL_ENCRYPTION_KEY = os.environ.get('CREDENTIAL_ENCRYPTION_KEY')
KIS_BASE_URL = "https://openapi.koreainvestment.com:9443"  # 실전투자 서버

# 한국수출입은행(koreaexim.go.kr) OpenAPI - 환전 고시 환율(매매기준율). KIS API에는 은행 고시
# 환율(하나은행 기준 등) 데이터가 없어 헤더 지수 티커의 "환전 고시 환율" 항목만 이 API를 쓴다.
# https://www.koreaexim.go.kr/ir/HPHKIR019M01
EXIM_AUTH_KEY = os.environ.get('EXIM_AUTH_KEY')

# DART(전자공시시스템) Open API - 상장기업 공시 데이터. https://opendart.fss.or.kr
DART_API_KEY = os.environ.get('DART_API_KEY')

# Gmail SMTP (회원가입/마이페이지 이메일 인증 메일 발송용, articles/email_utils.py 참고)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'NextFinUp <{EMAIL_HOST_USER}>'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# deploy/run_job.sh(articles.management.commands.notify_failure)는 cron 파이프라인이 조용히
# 실패했을 때(OOM kill 등) 여기로 이메일을 보낸다 — 이건 그대로 유지.
ADMINS = [('NextFinUp Admin', 'banks@naver.com')]

# DEBUG=False일 때 Django 기본 로깅 설정은 django 로거(500 에러, 잘못된 Host 헤더로 인한
# DisallowedHost 등)를 ADMINS로 메일 발송한다(mail_admins 핸들러) — 그런데 봇이 임의의 Host
# 헤더로 스캔할 때마다("Invalid HTTP_HOST header: 'testserver'" 같은) 관리자 메일함이 스팸으로
# 도배되는 문제가 실제로 있어(2026-08-18), mail_admins를 DBErrorLogHandler로 바꿔 이메일 대신
# SystemErrorLog 테이블에 쌓고 /admin/에서 조회하도록 했다. disable_existing_loggers=False로
# 둬서 django.server(runserver 로그) 등 여기서 언급 안 한 다른 로거는 Django 기본값 그대로 둔다.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'db_error': {
            'level': 'ERROR',
            'class': 'articles.logging_handlers.DBErrorLogHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'db_error'],
            'level': 'INFO',
        },
    },
}

# 앞단 프록시(Cloudflare 등)가 X-Forwarded-Proto 헤더로 원 요청의 스킴을 전달해준다는 전제 하에,
# request.build_absolute_uri() 등이 https로 올바르게 URL을 생성하도록 함
# (소셜 로그인 redirect_uri가 http://로 잘못 생성되어 KOE006/redirect_uri_mismatch가 나던 문제)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# DEBUG=True인 로컬 개발(http://localhost)에서는 비활성화하고, DEBUG=False로 배포될 때만
# 강제한다 — 위 SECURE_PROXY_SSL_HEADER 덕분에 프록시 뒤에서도 요청 스킴이 https로 올바르게
# 인식되므로, 세션/CSRF 쿠키를 https에서만 전송하고 http 요청은 https로 리다이렉트해도 안전하다.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
